name: Gamgyuls-Be server CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        # run: ./gradlew clean build
        run: ./gradlew clean build -x test # 테스트 Skip
      # 디렉토리 생성
      - name: Make Directory
        run: mkdir -p deploy

      # Jar 파일 복사
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy

      # AppSpec 파일 복사
      - name: Copy AppSpec file
        run: cp ./appspec.yml ./deploy/

      # Deploy script 복사
      - name: Copy deploy script
        run: cp ./scripts/deploy.sh ./deploy/

      - name: Make zip file
        run: zip -r ./jejugamgyuls.zip ./deploy
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./jejugamgyuls.zip s3://jejugamgyuls/

    # Deploy
      - name: Deploy
        env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
         aws deploy create-deployment \
         --application-name jejugamgyuls \
         --deployment-group-name jejugamgyuls-group \
         --file-exists-behavior OVERWRITE \
         --s3-location bucket=jejugamgyuls,bundleType=zip,key=jejugamgyuls.zip \
         --region ap-northeast-2
